package main;

import java.awt.Cursor;

/**
 *
 * @author cesista
 */
public class Hackathon extends javax.swing.JFrame {

    /**
     * Creates new form Hackathon
     */
    public Hackathon() {
        initComponents();
        btn_government.setOpaque(false);
        btn_government.setContentAreaFilled(false);
        btn_government.setBorderPainted(false);
        btn_government.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn_survivor.setOpaque(false);
        btn_survivor.setContentAreaFilled(false);
        btn_survivor.setBorderPainted(false);
        btn_survivor.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_government = new javax.swing.JButton();
        btn_survivor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        btn_government.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_government_onClick(evt);
            }
        });
        getContentPane().add(btn_government);
        btn_government.setBounds(560, 640, 310, 60);

        btn_survivor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_survivor_onClick(evt);
            }
        });
        getContentPane().add(btn_survivor);
        btn_survivor.setBounds(560, 560, 310, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeph SAME SIZE.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_government_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_government_onClick
        new Government().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_government_onClick

    private void btn_survivor_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_survivor_onClick
        new Survivor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_survivor_onClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hackathon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_government;
    private javax.swing.JButton btn_survivor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
